"""empty message

Revision ID: e87445e4adce
Revises: 6aa45d104ab0
Create Date: 2021-07-13 12:18:23.732212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87445e4adce'
down_revision = '6aa45d104ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_product', sa.Column('tax', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_product', 'tax')
    # ### end Alembic commands ###
